# Generated by Django 3.2.12 on 2022-02-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20)),
                ('car_year', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='car_make',
            field=models.CharField(max_length=20),
        ),
    ]
