# Generated by Django 3.2.12 on 2022-02-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempreg', '0002_auto_20220202_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
