# Generated by Django 3.0.14 on 2022-04-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempreg', '0002_auto_20220405_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
