# Generated by Django 3.2.12 on 2022-02-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempreg', '0003_auto_20220207_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_vin', models.CharField(max_length=100)),
                ('car_year', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'cars',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
