# Generated by Django 3.0.14 on 2022-04-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempreg', '0003_auto_20220405_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tempreg_id',
        ),
    ]
