# Generated by Django 3.0.14 on 2022-04-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempreg', '0003_auto_20220311_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'permissions': [('special_status', 'Can view user')], 'verbose_name_plural': 'car'},
        ),
    ]
