# Generated by Django 3.2.12 on 2022-02-08 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tempreg', '0004_auto_20220208_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars_info',
            options={'ordering': ['car_name'], 'verbose_name_plural': 'cars'},
        ),
        migrations.AddField(
            model_name='cars_info',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
