# Generated by Django 3.0.14 on 2022-04-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempreg', '0004_auto_20220404_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name_plural': 'car'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('special_status', 'Can view user')], 'verbose_name_plural': 'profile'},
        ),
    ]
