# Generated by Django 3.2.12 on 2022-02-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempreg', '0007_auto_20220212_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuserimages',
            name='contact',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
