# Generated by Django 3.2.12 on 2022-02-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempreg', '0008_profileuserimages_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuserimages',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
