# Generated by Django 3.2.12 on 2022-02-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempreg', '0009_profileuserimages_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimages',
            options={'verbose_name_plural': 'CarImages'},
        ),
        migrations.AlterModelOptions(
            name='profileuserimages',
            options={'verbose_name_plural': 'ProfileUserImages'},
        ),
    ]
