# Generated by Django 3.2.12 on 2022-02-12 20:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tempreg', '0010_auto_20220212_2029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileUserImages',
            new_name='ProfileUser',
        ),
        migrations.AlterModelOptions(
            name='carimages',
            options={'verbose_name_plural': 'Car Images'},
        ),
        migrations.AlterModelOptions(
            name='profileuser',
            options={'verbose_name_plural': 'Profile User'},
        ),
    ]
