# Generated by Django 3.2.12 on 2022-02-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempreg', '0011_auto_20220212_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name=''),
            preserve_default=False,
        ),
    ]
