# Generated by Django 3.2.12 on 2022-02-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempreg', '0013_alter_profileuser_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarImages',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cars_info',
        ),
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
