# Generated by Django 3.2.12 on 2022-02-13 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tempreg', '0015_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('left_side', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('back_image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('right_side', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
