# Generated by Django 3.2.12 on 2022-02-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempreg', '0018_alter_profile_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'gallery'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'profile'},
        ),
    ]
