# Generated by Django 3.2.12 on 2022-02-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempreg', '0020_auto_20220214_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('vin', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'car',
            },
        ),
    ]
